# inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

require:
  - rubocop-rspec
  - rubocop-rails

FactoryBot/AttributeDefinedStatically:
  Enabled: true

Layout/ClassStructure:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/LineLength:
  Max: 125

Lint/EmptyWhen:
  Enabled: false

Lint/InheritException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10
  Enabled: true

Metrics/BlockLength:
  Max: 50
  ExcludedMethods:
    - aasm

Metrics/MethodLength:
  CountComments: false
  Max: 50

Rails:
  Enabled: true

# TODO enable when fixed
Rails/ActiveRecordOverride:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/SaveBang:
  AllowImplicitReturn: true

Rails/SkipsModelValidations:
  Whitelist:
    - touch

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - require
    - redirect_to
    - raise

Style/NumericPredicate:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
