# Feel free to delete these and replace with your workflow

name: Rubocop

on:
  pull_request:
    branches: [ "*" ]

jobs:
  action_default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rubocop Linter Action - Default
      uses: andrewmcodes/rubocop-linter-action@v3.0.0 # Replace with version, branch, or commit sha if needed e.g. `andrewmcodes/rubocop-linter-action@v3.1.0`
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
